[opener]
zathura = [
    { run = '/opt/homebrew/bin/zathura "$@"', orphan = true, desc = "Zathura" }
]

[open]
prepend_rules = [
    { mime = "application/pdf", use = "zathura" },
    { url = "*.epub", use = "zathura" }
]
